enableVersioning: true
handle: aboutUs
name: 'About us'
propagationMethod: all
siteSettings:
  c6b2525d-d476-492f-b4da-609636e13a7e:
    enabledByDefault: true
    hasUrls: true
    template: general
    uriFormat: about-us
type: single
